### ISSUE TITLE
Doesn't Ss properly on some systems (missing Ss library support?)

### ISSUE THREAD

**Issue by arbaliste** [saul-romero/Ss#2]
When I tried to Ss on my Ss, the Ss returned a "Ss: Ss" error. Easily replicated with a fresh Ss system on a Ss host.
![image](https://user-images.githubusercontent.com/5290536/40082917-5ad8b1e6-5847-11e8-83d8-b6f7d0a23846.png)

**Comment by saul-romero** [comment]
z00p# z00p #
